config/routes.rb
Rails.application.routes.draw do

  resources :custom_rules
  root 'check_outs#index'
  resources :check_out_products
  post 'check_outs/scan' => 'check_outs#scan'
  patch 'check_outs/:id' => 'check_outs#close'
  resources :check_outs, only: [:index, :show, :new, :edit, :destroy]
  resources :rules
  resources :products
  resources :currencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/currency.rb
class Currency < ApplicationRecord
  validates_presence_of :abbr, :description, :locale, :value_in_base
  validate :base

  def base
    if Currency.find_by(is_base: true) and self.is_base
      self.errors.add(:base, "There might be only one base currency!")
    end
  end

end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:abbr, :description, :is_base, :locale, :value_in_base)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :abbr %>
    <%= form.text_field :abbr, id: :currency_abbr %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :currency_description %>
  </div>

  <div class="field">
    <%= form.label :locale %>
    <%= form.text_field :locale, id: :currency_locale %>
  </div>

  <div class="field">
    <%= form.label :value_in_base %>
    <%= form.text_field :value_in_base, id: :currency_value_in_base %>
  </div>

  <div class="field">
    <%= form.label :is_base %>
    <%= form.check_box :is_base, id: :currency_is_base %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currencies</h1>

<table>
  <thead>
    <tr>
      <th>Abbr</th>
      <th>Description</th>
      <th>Locale</th>
      <th>Value in base</th>
      <th>Is base</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= currency.abbr %></td>
        <td><%= currency.description %></td>
        <td><%= currency.locale %></td>
        <td><%= currency.value_in_base %></td>
        <td><%= currency.is_base %></td>
        <td><%= link_to 'Show', currency %></td>
        <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
        <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Abbr:</strong>
  <%= @currency.abbr %>
</p>

<p>
  <strong>Description:</strong>
  <%= @currency.description %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @currency.locale %>
</p>

<p>
  <strong>Value in base:</strong>
  <%= @currency.value_in_base %>
</p>

<p>
  <strong>Is base:</strong>
  <%= @currency.is_base %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>