config/routes.rb
Rails.application.routes.draw do

  resources :custom_rules
  root 'check_outs#index'
  resources :check_out_products
  post 'check_outs/scan' => 'check_outs#scan'
  patch 'check_outs/:id' => 'check_outs#close'
  resources :check_outs, only: [:index, :show, :new, :edit, :destroy]
  resources :rules
  resources :products
  resources :currencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/custom_rule.rb
class CustomRule < ApplicationRecord
  validates_presence_of :rule, :product_id, :date_from, :date_to
  belongs_to :product
  validate :crossrule
  validate :dates_continuity

  def crossrule
    if self.coliding.count > 0
      self.errors.add(:base, "Another custom rule is set for that product, count and time range")
    end
  end


    def dates_continuity
      if self.date_to < self.date_from
        self.errors.add(:base, "Date from can't take place after date to")
      end
    end

    def coliding
      coliding_rules = Rule.where(product_id: self.product_id).
           where("date_from BETWEEN ? AND ? OR date_to BETWEEN ? AND ?",
                  self.date_from, self.date_to, self.date_from, self.date_to)
      coliding_rules = coliding_rules.where("id <> ?", self.id) if self.id
      coliding_rules
    end
end

app/controllers/custom_rules_controller.rb
class CustomRulesController < ApplicationController
  before_action :set_custom_rule, only: [:show, :edit, :update, :destroy]

  # GET /custom_rules
  # GET /custom_rules.json
  def index
    @custom_rules = CustomRule.all
  end

  # GET /custom_rules/1
  # GET /custom_rules/1.json
  def show
  end

  # GET /custom_rules/new
  def new
    @custom_rule = CustomRule.new
  end

  # GET /custom_rules/1/edit
  def edit
  end

  # POST /custom_rules
  # POST /custom_rules.json
  def create
    @custom_rule = CustomRule.new(custom_rule_params)

    respond_to do |format|
      if @custom_rule.save
        format.html { redirect_to @custom_rule, notice: 'Custom rule was successfully created.' }
        format.json { render :show, status: :created, location: @custom_rule }
      else
        format.html { render :new }
        format.json { render json: @custom_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_rules/1
  # PATCH/PUT /custom_rules/1.json
  def update
    respond_to do |format|
      if @custom_rule.update(custom_rule_params)
        format.html { redirect_to @custom_rule, notice: 'Custom rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_rule }
      else
        format.html { render :edit }
        format.json { render json: @custom_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_rules/1
  # DELETE /custom_rules/1.json
  def destroy
    @custom_rule.destroy
    respond_to do |format|
      format.html { redirect_to custom_rules_url, notice: 'Custom rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_rule
      @custom_rule = CustomRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_rule_params
      params.require(:custom_rule).permit(:product_id, :rule, :date_from, :date_to)
    end
end

app/helpers/custom_rules_helper.rb
module CustomRulesHelper
end

app/views/custom_rules/_form.html.erb
<%= form_with(model: custom_rule, local: true) do |form| %>
  <% if custom_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(custom_rule.errors.count, "error") %> prohibited this custom_rule from being saved:</h2>

      <ul>
      <% custom_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.select(:product_id, Product.all.collect {|p| [ p.description, p.id ] }, { include_blank: false }) %>
  </div>

  <div class="field">
    <%= form.label :rule %>
    <%= form.text_area :rule, id: :custom_rule_rule %>
  </div>

  <div class="field">
    <%= form.label :date_from %>
    <%= form.date_select :date_from, id: :custom_rule_date_from %>
  </div>

  <div class="field">
    <%= form.label :date_to %>
    <%= form.date_select :date_to, id: :custom_rule_date_to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/custom_rules/edit.html.erb
<h1>Editing Custom Rule</h1>

<%= render 'form', custom_rule: @custom_rule %>

<%= link_to 'Show', @custom_rule %> |
<%= link_to 'Back', custom_rules_path %>

app/views/custom_rules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Custom Rules</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Rule</th>
      <th>Date from</th>
      <th>Date to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_rules.each do |custom_rule| %>
      <tr>
        <td><%= custom_rule.product.description %></td>
        <td><%= custom_rule.rule %></td>
        <td><%= custom_rule.date_from %></td>
        <td><%= custom_rule.date_to %></td>
        <td><%= link_to 'Show', custom_rule %></td>
        <td><%= link_to 'Edit', edit_custom_rule_path(custom_rule) %></td>
        <td><%= link_to 'Destroy', custom_rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom Rule', new_custom_rule_path %>

app/views/custom_rules/new.html.erb
<h1>New Custom Rule</h1>

<%= render 'form', custom_rule: @custom_rule %>

<%= link_to 'Back', custom_rules_path %>

app/views/custom_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @custom_rule.product.description %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @custom_rule.rule %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @custom_rule.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @custom_rule.date_to %>
</p>

<%= link_to 'Edit', edit_custom_rule_path(@custom_rule) %> |
<%= link_to 'Back', custom_rules_path %>