config/routes.rb
Rails.application.routes.draw do

  resources :custom_rules
  root 'check_outs#index'
  resources :check_out_products
  post 'check_outs/scan' => 'check_outs#scan'
  patch 'check_outs/:id' => 'check_outs#close'
  resources :check_outs, only: [:index, :show, :new, :edit, :destroy]
  resources :rules
  resources :products
  resources :currencies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/check_out.rb
class CheckOut < ApplicationRecord
  validates_presence_of :final_total, :if => Proc.new { |a| !a.date_closed.nil? }
  has_many :check_out_products

  def initialize
    super
    self.date_started = DateTime.now
    self.save!
  end

  def scan(product_name)
    if product = Product.find_by("description = ?", product_name)
      CheckOutProduct.create(product_id: product.id, check_out_id: self.id, date_added: DateTime.now)
    else
      self.errors.add(:base, "Product wasn't found.")
      puts "Product wasn't found."
    end
  end

  def close
    self.date_closed = DateTime.now
    self.final_total = total
  end

  def total
    total = 0
    # iteruj po wszystkich pozycjach
    self.check_out_products.grouped_by_product.each do |check_out_product|
      # reguły ręczne mają priorytet
      custom_rule = CustomRule.where("product_id = ? AND date_from <= ? AND date_to >= ?",
                     check_out_product.product_id, self.date_started, self.date_started).first
      if custom_rule
        eval(custom_rule.rule)
      # jeżeli brak ręcznych liczymyu normalnie
      else
        rules = Rule.where("product_id = ? AND count <= ? AND date_from <= ? AND date_to >= ?",
                     check_out_product.product_id, check_out_product.product_count,
                     self.date_started, self.date_started).
                     order(count: :desc)
        count_used_on_rules = 0
        # zastosuj reguły ilościowe (największa możliwa ilość pierwsz)
        if rules.count > 0
          while (check_out_product.product_count - count_used_on_rules) >= rules.first.count
            if (check_out_product.product_count - count_used_on_rules) >= rules.last.count
              total += rules.last.price * rules.last.currency.value_in_base
              count_used_on_rules += rules.last.count
            else
              rules.pop
            end
          end
        end
        # dodaj produkty nie łapiące się na żadne reguły
        total += (check_out_product.product_count - count_used_on_rules) * check_out_product.product.price * check_out_product.product.currency.value_in_base
      end
    end
    total
  end
end

app/controllers/check_outs_controller.rb
class CheckOutsController < ApplicationController
  before_action :set_check_out, only: [:show, :edit, :close, :destroy, :scan]

  # GET /check_outs
  # GET /check_outs.json
  def index
    @check_outs = CheckOut.all
  end

  # GET /check_outs/1
  # GET /check_outs/1.json
  def show
  end

  # GET /check_outs/new
  def new
    @check_out = CheckOut.new
  end

  # GET /check_outs/1/edit
  def edit
  end

  def scan
    respond_to do |format|
      if @check_out.scan(params[:scan])
        format.html { redirect_to "/check_outs/#{@check_out.id}/edit", notice: "Scan successful." }
        format.json { render json: @check_out.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to "/check_outs/#{@check_out.id}/edit", id: @check_out.id,notice: "Product code invalid." }
        format.json { render json: @check_out.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /check_outs
  # POST /check_outs.json
  def close
    @check_out.close
    respond_to do |format|
      if @check_out.save
        format.html { redirect_to @check_out, notice: 'Check out was successfully closed.' }
        format.json { render :show, status: :created, location: @check_out }
      else
        format.html { render :edit }
        format.json { render json: @check_out.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_outs/1
  # DELETE /check_outs/1.json
  def destroy
    @check_out.check_out_products.each {|cop| cop.destroy}
    @check_out.destroy
    respond_to do |format|
      format.html { redirect_to check_outs_url, notice: 'Check out was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_out
      @check_out = CheckOut.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_out_params
      params.require(:check_out).permit(:date_started, :date_closed)
    end
end

app/helpers/check_outs_helper.rb
module CheckOutsHelper
end

app/views/check_outs/_form.html.erb
<%= form_with(url: "/check_outs/scan", local: true) do |form| %>
  <div class="field">
    <%= form.label :scan %>
    <%= form.text_field :scan %>
    <%= form.hidden_field :id, value: check_out.id %>
  </div>

  <div class="actions">
    <%= form.submit "Scan" %>
  </div>
<% end %>

<%= form_with(model: check_out, local: true) do |form| %>
  <% if check_out.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check_out.errors.count, "error") %> prohibited this check_out from being saved:</h2>

      <ul>
      <% check_out.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_started %>
    <%= form.date_select :date_started, id: :check_out_date_started %>
  </div>

  <div class="field">
    <%= form.label :date_closed %>
    <%= form.date_select :date_closed, id: :check_out_date_closed %>
  </div>

  <% @check_out_products = check_out.check_out_products %>
  <%= render partial: 'check_out_products/index' %>

  <p>
    <strong>Total (with promos):</strong>
    <%= number_to_currency(check_out.total, locale: Currency.find_by(is_base: true).locale) %>
  </p>

  <div class="actions">
    <%= form.submit "Close checkout" %>
  </div>
<% end %>

app/views/check_outs/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Check Out</h1>

<%= render 'form', check_out: @check_out %>

<%= link_to 'Show', @check_out %> |
<%= link_to 'Back', check_outs_path %>

app/views/check_outs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Check Outs</h1>

<table>
  <thead>
    <tr>
      <th>Date started</th>
      <th>Date closed</th>
      <th>Final total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_outs.each do |check_out| %>
      <tr>
        <td><%= check_out.date_started %></td>
        <td><%= check_out.date_closed %></td>
        <td><%= number_to_currency(check_out.final_total, locale: Currency.find_by(is_base: true).locale) %></td>
        <td><%= link_to 'Show', check_out %></td>
        <td><%= link_to 'Edit', edit_check_out_path(check_out) if check_out.date_closed.nil? %></td>
        <td><%= link_to 'Destroy', check_out, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check Out', new_check_out_path %>

app/views/check_outs/new.html.erb
<h1>New Check Out</h1>

<%= render 'form', check_out: @check_out %>

<%= link_to 'Back', check_outs_path %>

app/views/check_outs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date started:</strong>
  <%= @check_out.date_started %>
</p>

<p>
  <strong>Date closed:</strong>
  <%= @check_out.date_closed %>
</p>

<p>
  <strong>Final total:</strong>
  <%= number_to_currency(@check_out.final_total, locale: Currency.find_by(is_base: true).locale) %>
</p>

<% @check_out_products = @check_out.check_out_products %>
<%= render partial: 'check_out_products/index' %>

<%= link_to 'Edit', edit_check_out_path(@check_out) %> |
<%= link_to 'Back', check_outs_path %>